world: de_dust2
competitive:
  de_dust2:
    spawnpoints:
      T:
        one:
          x: -13
          y: 46
          z: -551
        two:
          x: -9
          y: 46
          z: -551
        three:
          x: -9
          y: 46
          z: -554
        four:
          x: -13
          y: 46
          z: -554
        five:
          x: -1
          y: 46
          z: -557
      CT:
        one:
          x: -31
          y: 40
          z: -469
        two:
          x: -35
          y: 40
          z: -469
        three:
          x: -39
          y: 40
          z: -469
        four:
          x: -37
          y: 40
          z: -471
        five:
          x: -33
          y: 40
          z: -471