world: de_dust2
competitive:
  de_dust2:
    spawnpoints:
      T:
        one:
          x: 0
          y: 64
          z: 0
        two:
          x: 0
          y: 64
          z: 0
        three:
          x: 0
          y: 64
          z: 0
        four:
          x: 0
          y: 64
          z: 0
        five:
          x: 0
          y: 64
          z: 0
      CT:
        one:
          x: 0
          y: 64
          z: 0
        two:
          x: 0
          y: 64
          z: 0
        three:
          x: 0
          y: 64
          z: 0
        four:
          x: 0
          y: 64
          z: 0
        five:
          x: 0
          y: 64
          z: 0