world: de_dust2
competitive:
  de_dust2:
    spawnpoints:
      T:
        one:
          x: -36
          y: 9
          z: -2
        two:
          x: -32
          y: 9
          z: -2
        three:
          x: -28
          y: 9
          z: -2
        four:
          x: -30
          y: 9
          z: -5
        five:
          x: -34
          y: 9
          z: -5
      CT:
        one:
          x: -49
          y: 3
          z: 80
        two:
          x: -53
          y: 3
          z: 80
        three:
          x: -57
          y: 3
          z: 80
        four:
          x: -55
          y: 3
          z: 78
        five:
          x: -51
          y: 3
          z: 78