name: MineStrike
main: com.mcworldmap.play.MineStrike.MineStrike
version: 1.0
commands:
   join:
      description: Join a team
      usage: /join [T|CT]
      permission: MineStrike.join
      permission-message: You can't join a team
   buy:
      description: Buy stuff
      usage: /buy [weaponName]
      permission: MineStrike.buy
      permission-message: You can't buy stuff
   start:
      description: Start game
      usage: /start [gameType]
      permission: MineStrike.start
      permission-message: You can't start the game
   scoreboard:
      description: Display scoreboard
      usage: /scoreboard
      permission: MineStrike.scoreboard
      permission-message: wololo